---
# Providers shared across all platform-xp XRD repos.
# Repo-specific providers are declared in each repo's own provider.yaml.
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-aws-ec2
spec:
  package: xpkg.upbound.io/upbound/provider-aws-ec2:v1.21.0
  runtimeConfigRef:
    name: provider-aws-irsa
